### ISSUE TITLE
Unable to run project

### ISSUE THREAD

**Issue by voipiran** [Kol007/MoniAst#33]
**Describe the bug**
hi there,
I am trying to run your project on Issabel PBX.
Every steps goes Ok till:
node /opt/vi-operatorpanel/index.js

after run Node and index.js I have got this output:

```
[root@issabel voiz-installation]# node /opt/vi-operatorpanel/index.js
Express server started on port 40382 at ::
(node:7244) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
error with creating default user: MongooseError [ValidationError]: User validation failed: role: `10` is not a valid enum value for path `role`.
    at new ValidationError (/opt/vi-operatorpanel/node_modules/mongoose/lib/error/validation.js:28:11)
    at model.Document.invalidate (/opt/vi-operatorpanel/node_modules/mongoose/lib/document.js:1683:32)
    at /opt/vi-operatorpanel/node_modules/mongoose/lib/document.js:1555:17
    at validate (/opt/vi-operatorpanel/node_modules/mongoose/lib/schematype.js:784:7)
    at /opt/vi-operatorpanel/node_modules/mongoose/lib/schematype.js:829:11
    at Array.forEach (<anonymous>)
    at SchemaString.SchemaType.doValidate (/opt/vi-operatorpanel/node_modules/mongoose/lib/schematype.js:789:19)
    at /opt/vi-operatorpanel/node_modules/mongoose/lib/document.js:1553:9
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  errors: {
    role: MongooseError [ValidatorError]: `10` is not a valid enum value for path `role`.
        at new ValidatorError (/opt/vi-operatorpanel/node_modules/mongoose/lib/error/validator.js:25:11)
        at validate (/opt/vi-operatorpanel/node_modules/mongoose/lib/schematype.js:782:13)
        at /opt/vi-operatorpanel/node_modules/mongoose/lib/schematype.js:829:11
        at Array.forEach (<anonymous>)
        at SchemaString.SchemaType.doValidate (/opt/vi-operatorpanel/node_modules/mongoose/lib/schematype.js:789:19)
        at /opt/vi-operatorpanel/node_modules/mongoose/lib/document.js:1553:9
        at processTicksAndRejections (internal/process/task_queues.js:79:11) {
      properties: [Object],
      kind: 'enum',
      path: 'role',
      value: '10',
      reason: undefined,
      '$isValidatorError': true
    }
  },
  _message: 'User validation failed'
}
Created default user: admin/admin



```

also this is my config.js file:

```
module.exports = {
  port: process.env.PORT || 3001,
  host: '0.0.0.0', // comment it, for listen only on localhost(127.0.0.1), needed reverse-proxy, nginx as example

  secret: '123456',
  database: 'mongodb://localhost:27027/MoniAst',

  AMI: {
    port: 5038,
    ip: '127.0.0.1',
    login: 'phpconfig',
    pass: 'php[onfig'
  }
};



```

** I have change mongo db port to 27027
**also i dont know what should i insert in secret, this is my root password now.

thank you in advanced.

**Comment by hamedkouhfallah** [comment]
Then,
I tried to run with "pm2 start ecosystem.config.js --env production".
Now I can see login page but I can not login with admin admin

![image](https://user-images.githubusercontent.com/54766086/92006827-75f43680-ed5a-11ea-89f4-100549afd0d8.png)

**Comment by Kol007** [comment]
@voipiran Hello.
Fixed in latest version.

**Comment by Kol007** [comment]
@voipiran Did you have a chance to try the fixed version?

**Comment by voipiran** [comment]
Hi,
Sorry for my delay,
Now I installed again in this case i can not open web ui...
This is what i did:
Install mongo
Install Nodejs

also this is config.js:

![image](https://user-images.githubusercontent.com/54766086/95203140-330cff00-07ef-11eb-9028-56ae60d324c4.png)


and I started project with: 
pm2 start ecosystem.config.js --env production

![image](https://user-images.githubusercontent.com/54766086/95203204-45873880-07ef-11eb-8b6d-e7b2368a7c29.png)


so I tried to open via web on 3001 port:

![image](https://user-images.githubusercontent.com/54766086/95203249-589a0880-07ef-11eb-9788-ade14afdb855.png)



Please let me know what can i do to find what is the problem?

thanks

**Comment by voipiran** [comment]
sorry
it was my fault
my db port was incorrect.

It is running OK

**Comment by Kol007** [comment]
I'm glad that you start it.
