### ISSUE TITLE
it's impossible

### ISSUE THREAD

**Issue by Marcelas751** [Kol007/MoniAst#58]
![image](https://user-images.githubusercontent.com/40628504/133082100-883ef246-0819-4544-99fc-60a12b2d8036.png)
In Queues after hangup (after call with 1076) i see this. Fixes only if i update page (F5). Browser Google Chrome

**Comment by Kol007** [comment]
![image](https://user-images.githubusercontent.com/5255600/134019632-e3dc7033-800e-4895-b3bd-d347a37179f4.png)

Hello.
Very strange situation. 
1) Why first "Operator card" hasn't internal sip number;
2) Why is there a duplicate for "Operator card";
3) Why there are cursor (like `contenteditable="true"` block); (I think you've changed something in DOM Tree from chrome dev tools)

**Comment by Kol007** [comment]
stale
