### ISSUE TITLE
Implement PJSip support

### ISSUE THREAD

**Issue by pieter-vos** [Kol007/MoniAst#6]
**Is your feature request related to a problem? Please describe.**
PJSip is getting more extended, many setups are using PJSip exclusively. 

**Describe the solution you'd like**
Getting support for both SIP as PJSIP stacks.

**Describe alternatives you've considered**
No alternatives afaik

**Additional context**
MoniAst is a great product, I've tried it out on a old setup with SIP stack, would be great to get it working with new PJSip stack.

**Comment by Kol007** [comment]
Hello!
Can you try the last commit for PJ SIP.
