### ISSUE TITLE
configuration guide to run on Issabel or Freepbx

### ISSUE THREAD

**Issue by voipiran** [Kol007/MoniAst#62]
**Is your feature request related to a problem? Please describe.**
Hi,
The moniast Instaaltion is not sutable for Issabel or Freepbx,
I think after installation we should do some things to run Moniast throw Apache.
is There any configuration guide to run on Issabel or Freepbx?

Thanks

**Comment by Kol007** [comment]
Hello.
It was developed with Freepbx on the server, so there is no problem with it.
Of course, you should config your proxy server, MoniAst run on some port at localhost.
On the homepage there are example for Nginx;
